// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_3VyCGKdvhacNr3HxfqAO2q62pVS7bBA',
    appId: '1:1018256705566:web:d362a0eb0f035cb15a860f',
    messagingSenderId: '1018256705566',
    projectId: 'smart-lesson-plan-app',
    authDomain: 'smart-lesson-plan-app.firebaseapp.com',
    storageBucket: 'smart-lesson-plan-app.firebasestorage.app',
    measurementId: 'G-88RRYSPX5F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGzpoBTA0e51zuZvjALSUqP29FQoEl-VQ',
    appId: '1:1018256705566:android:38d1b385e0c52e1d5a860f',
    messagingSenderId: '1018256705566',
    projectId: 'smart-lesson-plan-app',
    storageBucket: 'smart-lesson-plan-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOuXkye7sCMss7PMKh7lbX72XWY-1tkEw',
    appId: '1:1018256705566:ios:7794435ad491438e5a860f',
    messagingSenderId: '1018256705566',
    projectId: 'smart-lesson-plan-app',
    storageBucket: 'smart-lesson-plan-app.firebasestorage.app',
    iosBundleId: 'com.deped.smartlp.smartLessonPlan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOuXkye7sCMss7PMKh7lbX72XWY-1tkEw',
    appId: '1:1018256705566:ios:7794435ad491438e5a860f',
    messagingSenderId: '1018256705566',
    projectId: 'smart-lesson-plan-app',
    storageBucket: 'smart-lesson-plan-app.firebasestorage.app',
    iosBundleId: 'com.deped.smartlp.smartLessonPlan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_3VyCGKdvhacNr3HxfqAO2q62pVS7bBA',
    appId: '1:1018256705566:web:d29a37726de35cfe5a860f',
    messagingSenderId: '1018256705566',
    projectId: 'smart-lesson-plan-app',
    authDomain: 'smart-lesson-plan-app.firebaseapp.com',
    storageBucket: 'smart-lesson-plan-app.firebasestorage.app',
    measurementId: 'G-KCYSJLEKSC',
  );
}
